// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw8gaqO1K43X3AwouK7ZyOnzjEFDmImgo',
    appId: '1:216392954827:web:0657d3d5af574e0ecefc4e',
    messagingSenderId: '216392954827',
    projectId: 'baitaplon-34432',
    authDomain: 'baitaplon-34432.firebaseapp.com',
    storageBucket: 'baitaplon-34432.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv7Y3JFz0i9VZMdbxHzRQK76nmKSk_q_o',
    appId: '1:216392954827:android:d434d5dc9c92e035cefc4e',
    messagingSenderId: '216392954827',
    projectId: 'baitaplon-34432',
    storageBucket: 'baitaplon-34432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-068j3RcSlY092Bj5CFjAAwxPqfDa0s',
    appId: '1:216392954827:ios:8309b492e1d66847cefc4e',
    messagingSenderId: '216392954827',
    projectId: 'baitaplon-34432',
    storageBucket: 'baitaplon-34432.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-068j3RcSlY092Bj5CFjAAwxPqfDa0s',
    appId: '1:216392954827:ios:8309b492e1d66847cefc4e',
    messagingSenderId: '216392954827',
    projectId: 'baitaplon-34432',
    storageBucket: 'baitaplon-34432.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw8gaqO1K43X3AwouK7ZyOnzjEFDmImgo',
    appId: '1:216392954827:web:1812315af961d061cefc4e',
    messagingSenderId: '216392954827',
    projectId: 'baitaplon-34432',
    authDomain: 'baitaplon-34432.firebaseapp.com',
    storageBucket: 'baitaplon-34432.appspot.com',
  );
}
